#!/bin/bash
#
# Name:         oim.bash
#
# Function:     This script runs Oracle incremental backup using DD BoostFS and fastcopy.
#               It has the following scripts and run in the following sequence.
#               incremerge.bash  			-- Managed by Oracle DBA
#               incremerge-fastcopy.bash			-- Managed by DD admin 
#               <host>.<oracle-sid>.setretention.bash  	-- generated automatically  
#               <host>.<oracle-sid>.catalog.bash  	-- generated automatically 
#
# Show Usage: run the command to show the usage
#
# Changes:
# 12/19/18 Diana Yang   New script
#
# footnotes:
# If you use this script and would like to get new code when any fixes are added,
# please send an email to diana.h.yang@dell.com. Whenever it is updated, I will send
# you an alert.
#################################################################
## Oracle backup
function show_usage {
echo "usage: oim.bash -o <OIM oracle configuration file> -d <OIM DD fastcopy configuration file> "
echo " -o : OIM oracle configuration file"
echo " -d : OIM DD fastcopy configuration file"
}

while getopts ":o:d::" opt; do
  case $opt in
    o ) ofile=$OPTARG;;
    d ) dfile=$OPTARG;;
  esac
done

if test $ofile && test $dfile 
then
  :
else
  show_usage
  exit 1
fi

DIRcurrent=$0
DIR=`echo $DIRcurrent |  awk 'BEGIN{FS=OFS="/"}{NF--; print}'`
if [[ $DIR = '.' ]]; then
   DIR=`pwd`
fi

#echo $DIR

if [[ -e ${DIR}/$ofile ]]; then
   . ${DIR}/$ofile
fi

date
echo "RUN Oracle incremental backup. log is in ${DIR}/log"

if [[ -n $server ]];then
   echo ${DIR}/incremerge.bash -h $host -o $oracle_sid -w $retday -t $type -m $mount -s $server 
   ${DIR}/incremerge.bash -h $host -o $oracle_sid -w $retday -t $type -m $mount -s $server 
else
   echo ${DIR}/incremerge.bash -h $host -o $oracle_sid -w $retday -t $type -m $mount
   ${DIR}/incremerge.bash -h $host -o $oracle_sid -w $retday -t $type -m $mount
fi

if [ $? -ne 0 ]; then
    echo "Oracle backup failed"
    exit 1
fi

echo ""

## DD fastcopy 

if [[ -e ${DIR}/$dfile ]]; then
   . ${DIR}/$dfile
fi

echo "RUN fastcopy. log is in $dddir/log"
if [[ -n $server ]];then
   echo ssh oracle@$server "sudo -u $ddunixuser $dddir/incremerge-fastcopy.bash -d $dd -u $dduser -m $mount -h $host -o $oracle_sid -k $retday"
   ssh oracle@$server "sudo -u $ddunixuser $dddir/incremerge-fastcopy.bash -d $dd -u $dduser -m $mount -h $host -o $oracle_sid -k $retday"
else
   echo sudo -u $ddunixuser $dddir/incremerge-fastcopy.bash -d $dd -u $dduser -m $mount -h $host -o $oracle_sid -k $retday
   sudo -u $ddunixuser $directory/incremerge-fastcopy.bash -d $dd -u $dduser -m $mount -h $host -o $oracle_sid -k $retday
fi

if [ $? -ne 0 ]; then
    echo "DD fastcopy failed"
    exit 1
fi

echo ""

## set retention lock. <host>.<oracle sid>.setretention.bash script is generated by incremerge-fastcopy bash script
echo "RUN set retention lock script"
echo "If retention lock is not enabled, the follow script has no effect"
echo "You can find out whether retention lock is enabled or not by check logs in dd log"
if [[ -n $server ]]; then
   ssh oracle@$server "ls /tmp/${host}.${oracle_sid}.setretention.bash"
#  ssh oracle@$server "/tmp/${host}.${oracle_sid}.setretention.bash"
else
   ls /tmp/${host}.${oracle_sid}.setretention.bash
#  /tmp/${host}.${oracle_sid}.setretention.bash
fi

echo ""

#if [ $? -ne 0 ]; then
#    echo "set retention lock failed"
#    exit 1
#fi

## catalog the fastcopied file. <host>.<oracle sid>.catalog.bash script is generated by incremerge.bash script
echo "RUN catalog command to catalog the fastcopied file"
echo ${DIR}/${host}.${oracle_sid}.catalog.bash
${DIR}/${host}.${oracle_sid}.catalog.bash

if [ $? -ne 0 ]; then
    echo "Oracle catalog failed"
    exit 1
fi
date
